server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  gzip on;
  error_page 404 /404.html;
  location / { try_files $uri $uri/ $uri.html =404; }
  location ~ ^/llms/(.+)$ { default_type text/plain; charset utf-8; try_files $uri $uri/ $uri.md =404; }
}
