from __future__ import annotations

from importlib.resources import files
from typing import Any, cast

from fastapi import FastAPI
from fastapi.openapi.docs import get_swagger_ui_html
from fastapi.openapi.utils import get_openapi
from fastapi.responses import HTMLResponse, JSONResponse, Response

DOCS_URL = "/docs"
OPENAPI_URL = "/openapi.json"
SWAGGER_ASSET_PREFIX = "/static/swagger"


def mount_swagger_ui(app: FastAPI, public_model: str) -> None:
    static_dir = files("ai_gateway.proxy.static.swagger")
    assets = {
        "swagger-ui-bundle.js": (static_dir.joinpath("swagger-ui-bundle.js").read_bytes(), "application/javascript"),
        "swagger-ui.css": (static_dir.joinpath("swagger-ui.css").read_bytes(), "text/css"),
        "favicon.png": (static_dir.joinpath("favicon.png").read_bytes(), "image/png"),
    }

    @app.get(f"{SWAGGER_ASSET_PREFIX}/{{asset_name}}", include_in_schema=False)
    async def swagger_asset(asset_name: str) -> Response:
        asset = assets.get(asset_name)
        if asset is None:
            return JSONResponse(
                status_code=404,
                content={
                    "error": {
                        "message": "The requested resource was not found.",
                        "type": "invalid_request_error",
                        "param": None,
                        "code": "not_found",
                    }
                },
            )
        return Response(asset[0], media_type=asset[1])

    @app.get(OPENAPI_URL, include_in_schema=False)
    async def openapi_json() -> JSONResponse:
        return JSONResponse(build_public_openapi_schema(app, public_model))

    @app.get(DOCS_URL, include_in_schema=False)
    async def swagger_ui() -> HTMLResponse:
        return get_swagger_ui_html(
            openapi_url=OPENAPI_URL,
            title="AI Gateway - Swagger UI",
            swagger_js_url=f"{SWAGGER_ASSET_PREFIX}/swagger-ui-bundle.js",
            swagger_css_url=f"{SWAGGER_ASSET_PREFIX}/swagger-ui.css",
            swagger_favicon_url=f"{SWAGGER_ASSET_PREFIX}/favicon.png",
            swagger_ui_parameters={"tryItOutEnabled": True, "displayRequestDuration": True},
        )


def build_public_openapi_schema(app: FastAPI, public_model: str) -> dict[str, Any]:
    cached = getattr(app.state, "public_openapi_schema", None)
    if cached is not None:
        return cast(dict[str, Any], cached)
    schema = get_openapi(
        title="AI Gateway",
        version="1.0.0",
        description=(
            "Anonymous OpenAI-compatible chat gateway for one operator-configured model. "
            "Streaming responses use raw server-sent events and end with data: [DONE]."
        ),
        routes=app.routes,
    )
    schema["openapi"] = "3.1.0"
    components = schema.setdefault("components", {})
    components.setdefault("parameters", {})["OptionalPlaceholderAuthorization"] = {
        "in": "header",
        "name": "Authorization",
        "required": False,
        "description": "Optional non-secret compatibility placeholder; never used for authorization.",
        "schema": {"type": "string", "pattern": "^Bearer .+$"},
    }
    components.setdefault("headers", {})["RequestId"] = {
        "description": "Opaque support correlation identifier generated by the gateway.",
        "schema": {"type": "string", "format": "uuid"},
    }
    chat = schema["paths"]["/v1/chat/completions"]["post"]
    grounding_enabled = bool(app.state.proxy_config.liara_grounding_enabled)
    if grounding_enabled:
        chat["operationId"] = "createGroundedChatCompletion"
        metadata_schema = _liara_metadata_schema()
        components.setdefault("schemas", {})["LiaraAssistantMetadataV1"] = metadata_schema
        model_response = components["schemas"].get("ModelResponse")
        if isinstance(model_response, dict):
            model_response.setdefault("properties", {})["x_liara"] = {
                "$ref": "#/components/schemas/LiaraAssistantMetadataV1"
            }
        components["schemas"]["LiaraTerminalChunk"] = {
            "type": "object",
            "required": ["id", "object", "created", "model", "choices", "x_liara"],
            "properties": {
                "id": {"type": "string"},
                "object": {"const": "chat.completion.chunk"},
                "created": {"type": "integer"},
                "model": {"type": "string"},
                "choices": {"type": "array", "maxItems": 0},
                "x_liara": {"$ref": "#/components/schemas/LiaraAssistantMetadataV1"},
            },
        }
    chat["requestBody"]["content"]["application/json"]["examples"] = {
        "basic": {"value": {"model": public_model, "messages": [{"role": "user", "content": "Hello"}]}},
        "streaming": {
            "value": {"model": public_model, "messages": [{"role": "user", "content": "Hello"}], "stream": True}
        },
    }
    chat["responses"]["200"]["content"]["text/event-stream"] = {
        "schema": {
            "type": "string",
            "description": "Ordered data events followed exactly once by data: [DONE].",
            **(
                {
                    "x-data-event-schema": {
                        "oneOf": [
                            {"type": "object", "description": "OpenAI-compatible delta chunk"},
                            {"$ref": "#/components/schemas/LiaraTerminalChunk"},
                        ]
                    }
                }
                if grounding_enabled
                else {}
            ),
        },
    }
    for path, method in (("/v1/models", "get"), ("/v1/chat/completions", "post")):
        operation = schema["paths"][path][method]
        operation.setdefault("parameters", []).append(
            {"$ref": "#/components/parameters/OptionalPlaceholderAuthorization"}
        )
    for path_item in schema["paths"].values():
        for operation in path_item.values():
            if isinstance(operation, dict):
                responses = operation.get("responses", {})
                responses.pop("422", None)
                for response in responses.values():
                    if isinstance(response, dict):
                        response.setdefault("headers", {})["x-request-id"] = {"$ref": "#/components/headers/RequestId"}
    app.state.public_openapi_schema = schema
    return schema


def _liara_metadata_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "schema_version",
            "documentation_revision",
            "intent",
            "answer_path",
            "citations",
            "next_steps",
            "reuse",
        ],
        "properties": {
            "schema_version": {"const": 1},
            "documentation_revision": {"type": "string", "pattern": "^[a-f0-9]{64}$"},
            "intent": {
                "type": "object",
                "additionalProperties": False,
                "required": ["kind", "missing_fields", "topic_changed"],
                "properties": {
                    "kind": {
                        "enum": [
                            "direct",
                            "complex",
                            "clarify",
                            "abstain",
                            "out_of_scope",
                            "elevated_risk",
                        ]
                    },
                    "missing_fields": {
                        "type": "array",
                        "maxItems": 5,
                        "uniqueItems": True,
                        "items": {
                            "enum": [
                                "service",
                                "runtime",
                                "version",
                                "environment",
                                "goal",
                                "error_context",
                            ]
                        },
                    },
                    "topic_changed": {"type": "boolean"},
                },
            },
            "answer_path": {"enum": ["generated", "clarification", "abstention", "exact_cache"]},
            "citations": {
                "type": "array",
                "maxItems": 12,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": [
                        "id",
                        "marker",
                        "passage_id",
                        "title",
                        "url",
                        "documentation_revision",
                        "validation",
                    ],
                    "properties": {
                        "id": {"type": "string", "pattern": "^c[1-9][0-9]?$"},
                        "marker": {"type": "integer", "minimum": 1, "maximum": 12},
                        "passage_id": {"type": "string", "minLength": 16, "maxLength": 128},
                        "title": {"type": "string", "minLength": 1, "maxLength": 240},
                        "url": {"type": "string", "pattern": "^https://docs\\.liara\\.ir/"},
                        "heading": {"type": ["string", "null"], "maxLength": 240},
                        "documentation_revision": {
                            "type": "string",
                            "pattern": "^[a-f0-9]{64}$",
                        },
                        "validation": {"const": "valid"},
                    },
                },
            },
            "next_steps": {"type": "array", "maxItems": 3},
            "workflow": {"type": ["object", "null"]},
            "reuse": {"enum": ["none", "retrieval", "reviewed_exact_answer"]},
        },
    }
